language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
before_script:
  - export PYTHONPATH=$PYTHONPATH:./
script:
  - py.test
after_success:
  - coveralls
